name: Deploy Infrastructure

on:
  workflow_dispatch:  # Ejecutar manualmente
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Configurar AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          
      - name: Terraform Init y Apply
        run: |
          cd infrastructure
          terraform init \
            -backend-config="bucket=terraform-state-scraper-ia" \
            -backend-config="region=us-east-2"
          terraform apply -auto-approve 